Pipfile.lock, breathecode/admissions/TODO.md, breathecode/admissions/serializers.py, breathecode/admissions/tests.py, breathecode/admissions/tests/mixins/__init__.py, breathecode/admissions/tests/mixins/admissions_test_case.py, breathecode/admissions/tests/urls/tests_academy.py, breathecode/admissions/tests/urls/tests_certificate.py, breathecode/admissions/tests/urls/tests_cohort.py, breathecode/admissions/tests/urls/tests_cohort_all.py, breathecode/admissions/tests/urls/tests_cohort_id.py, breathecode/admissions/tests/urls/tests_cohort_id_user_id.py, breathecode/admissions/tests/urls/tests_cohort_user.py, breathecode/admissions/urls.py, breathecode/admissions/views.py, breathecode/certificate/actions.py, breathecode/certificate/tests/actions/tests_certificate_screenshot.py, breathecode/certificate/tests/mixins/certificate_test_case.py, breathecode/events/models.py, breathecode/tests/mixins/__init__.py, breathecode/tests/mixins/date_formatter.py, breathecode/tests/mixins/development_environment.py, breathecode/tests/mocks/__init__.py, breathecode/tests/mocks/google_cloud_storage/__init__.py, breathecode/tests/mocks/google_cloud_storage/blob_mock.py, breathecode/tests/mocks/google_cloud_storage/bucket_mock.py, breathecode/tests/mocks/google_cloud_storage/client_mock.py, breathecode/tests/mocks/screenshotmachine/__init__.py, breathecode/tests/mocks/screenshotmachine/requests_mock.py, breathecode/utils.py
Diff of screenshot issue https://github.com/breatheco-de/apiv2/commit/d08536fc2c6a4b9d55c7ad831e4c3f68bfb26af3
=> Tests admissions, fix screenshot issue

Pipfile, Pipfile.lock, breathecode/activity/models.py, breathecode/activity/urls.py, breathecode/activity/views.py
=> Filtered cohort activities

README.md
- minor proposal on paragraph 137
=> Minor fixes (lines 59, 140)

breathecode/events/serializers.py, breathecode/events/urls.py, breathecode/events/views.py, breathecode/freelance/actions.py, breathecode/marketing/admin.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2141
=> Get Webhook endopoint

breathecode/events/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2141
=> Sort Webhooks by updated-at

breathecode/marketing/tasks.py, breathecode/marketing/tests/tasks/tests_add_event_slug_as_acp_tag.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2148
=> fix tag event issue

breathecode/feedback/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2503
=> fix like in reviews

breathecode/admissions/tests/urls/tests_academy_cohort.py, breathecode/admissions/tests/urls/tests_academy_cohort_id.py, breathecode/admissions/tests/urls/tests_academy_cohort_me.py, breathecode/admissions/views.py, breathecode/events/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2243
=> fix cache bugs

.github/workflows/dockerhub.yml, breathecode/authenticate/tests/urls/tests_github_callback.py, breathecode/authenticate/views.py
=> if a user does not exist in breathecode when it login with github, raise a error

README.md
According to the Misspell Challenge, I found a misspell in the README.md 's 40th line.
Has to change the word "webside" by "website".
=> In README.md file, change word webside by website on line 40. 

breathecode/authenticate/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3173
=> filter students by list of cohorts

breathecode/authenticate/forms.py, breathecode/authenticate/tests/urls/tests_member_invite_token.py, breathecode/authenticate/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3264
=> Fix password1 and password2 on invite link

breathecode/mentorship/tests/urls/tests_academy_service.py, breathecode/mentorship/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3175
=> Delete services in bulk

breathecode/admissions/serializers.py, breathecode/admissions/tests/urls/tests_cohort_id_user.py, breathecode/admissions/tests/urls/tests_cohort_id_user_id.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3042
=> Update the certificate generation validation

breathecode/mentorship/actions.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3201
=> change bills status when there is no recalculate

breathecode/mentorship/actions.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3363
=> fix bug at generate_mentor_bills

breathecode/certificate/actions.py, breathecode/certificate/tests/actions/tests_generate_certificate.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3350
=> Add unit tests to validate the mandatory_tasks

breathecode/marketing/serializers.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3464
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3475
=> add created_at

breathecode/marketing/tests/urls/tests_academy_lead.py, breathecode/marketing/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3577
=> Agregar utm source, utm term, location alias q los filtros

Procfile, breathecode/registry/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3413
=> Filters on article comment pipeline

breathecode/registry/actions.py, breathecode/registry/tests/actions/tests_clean_readme.py, breathecode/registry/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3692
=> add conditional to clean asset

breathecode/marketing/serializers.py, breathecode/marketing/tests/urls/tests_academy_tag_slug.py, breathecode/marketing/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3474
=> make update tag bulk

breathecode/events/tests/urls/tests_me.py, breathecode/events/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4295
=> add Active to filter

breathecode/events/serializers.py, breathecode/events/tests/urls/tests_academy_eventype.py, breathecode/events/tests/urls/tests_eventype.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4331
=> add fields to event-type serializer

breathecode/events/serializers.py, breathecode/events/tests/urls/tests_academy_eventype_slug.py, breathecode/events/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4312
=> added tests for event type put

breathecode/marketing/management/commands/retry_pending_leads.py, breathecode/marketing/tests/management/commands/tests_retry_pending_leads.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3489
=> Django Script to retry pending leads

breathecode/assignments/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4251
=> not allow users to update projects that doesnt belong to them

breathecode/admissions/views.py
Service: `GET /v1/admissions/cohort/all`
=> Included never_ends cohorts on upcoming filter

breathecode/marketing/caches.py, breathecode/marketing/views.py
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4797
=> technologies-filter

breathecode/provisioning/serializers.py, breathecode/provisioning/templates/provisioning_invoice.html, breathecode/provisioning/views.py
Pagination changed, layout changed, cre…ated_at added, the button changed
=> ProvisioingBillHTML modified. 

breathecode/admissions/tests/urls/tests_academy_cohort_user.py, breathecode/assignments/serializers.py
https://github.com/breatheco-de/breatheco-de/issues/5352
=> add updated_at to task small serializer

breathecode/assignments/views.py
https://github.com/breatheco-de/breatheco-de/issues/4694
=> add educational status filter to get tasks

breathecode/registry/views.py
https://github.com/breatheco-de/breatheco-de/issues/5948
=> add difficulty filter to assets

breathecode/registry/views.py
https://github.com/breatheco-de/breatheco-de/issues/5948
=> fix bug with lower case in difficulty param

breathecode/admissions/views.py
https://github.com/breatheco-de/breatheco-de/issues/5815
=> add slug parameter tu public syllabus version

breathecode/assignments/tests/urls/tests_user_me_task.py, breathecode/assignments/views.py, breathecode/celery.py
https://github.com/breatheco-de/breatheco-de/issues/6057
=> filter tasks by asset

breathecode/assignments/tests/urls/tests_user_me_task.py, breathecode/assignments/views.py, breathecode/registry/receivers.py, breathecode/registry/tasks.py
https://github.com/breatheco-de/breatheco-de/issues/6142
=> Update vercel cache

breathecode/registry/serializers.py, breathecode/registry/tests/urls/tests_asset.py, breathecode/registry/urls.py, breathecode/registry/views.py, breathecode/tests/mixins/generate_models_mixin/registry_models_mixin.py, breathecode/utils/api_view_extensions/extensions/lookup_extension.py, conftest.py
https://github.com/breatheco-de/breatheco-de/issues/6141
=> Asset technology serializer

breathecode/registry/tasks.py
https://github.com/breatheco-de/breatheco-de/issues/6142
=> fix wrong env variable on task

breathecode/registry/tests/urls/tests_asset.py
https://github.com/breatheco-de/breatheco-de/issues/6141
=> add lookp test to asset_tests

breathecode/registry/receivers.py, breathecode/registry/tasks.py
https://github.com/breatheco-de/breatheco-de/issues/6142
=> fix url for api endpoint

breathecode/authenticate/serializers.py
https://github.com/breatheco-de/breatheco-de/issues/5792
=> add conversion_info to serializer

breathecode/registry/views.py
https://github.com/breatheco-de/breatheco-de/issues/6510
=> add distinct to AssetView

breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/6208
=> fix bug at update user setting

breathecode/activity/tests/urls/v2/tests_report.py, breathecode/activity/views.py, breathecode/services/google_cloud/big_query.py
https://github.com/breatheco-de/breatheco-de/issues/5346
=> add date filters to academy_activity

breathecode/registry/serializers.py
https://github.com/breatheco-de/breatheco-de/issues/6492
=> add categories to small asset serializer

breathecode/authenticate/serializers.py
https://github.com/breatheco-de/breatheco-de/issues/6292
=> added new keys to conversion info

breathecode/authenticate/tests/urls/tests_user_profile.py, breathecode/authenticate/urls.py, breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/6196
=> add get profile id and put profile

breathecode/registry/serializers.py
https://github.com/breatheco-de/breatheco-de/issues/6492
=> add technologies to serializer

breathecode/events/serializers.py, breathecode/events/tests/urls/tests_academy_event_id.py
https://github.com/breatheco-de/breatheco-de/issues/6659
=> added free for all to academy event endpoint

breathecode/activity/tests/urls/v2/tests_academy_activity.py, breathecode/activity/views.py
https://github.com/breatheco-de/breatheco-de/issues/6693
=> add order to query params on academy activities report

breathecode/authenticate/tasks.py
https://github.com/breatheco-de/breatheco-de/issues/6754
=> allow async_validate_email_invite to receive more parameters

breathecode/events/tests/urls/tests_me_event_id_join.py, breathecode/events/tests/urls/tests_me_event_liveclass_join_hash.py, breathecode/mentorship/tests/urls_shortner/tests_meet_slug_service_slug.py, breathecode/utils/decorators/has_permission.py
=> Fix tests on mentorships consumables

breathecode/utils/decorators/has_permission.py
=> aded prints to debug

breathecode/events/tests/urls/tests_me_event_id_join.py, breathecode/utils/decorators/has_permission.py
=> Reformat Get more consumables functionality

breathecode/events/tests/urls/tests_me_event_id_join.py, breathecode/utils/decorators/has_permission.py
=> remove prints

breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/6812
=> Register user on rigobot when they sync their github account

breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/6812
=> Change endpoint to invite on rigobot registration

breathecode/mentorship/tests/urls/tests_academy_mentor.py, breathecode/mentorship/views.py
https://github.com/breatheco-de/breatheco-de/issues/6877
=> filter syllabus by comma separated sequence

breathecode/events/tests/urls/tests_me_event_id_join.py, breathecode/mentorship/tests/urls_shortner/tests_meet_slug_service_slug.py, breathecode/utils/decorators/has_permission.py
=> Add token to redirect link on get more consumables

breathecode/registry/serializers.py, breathecode/registry/tests/urls/tests_academy_asset.py, breathecode/registry/tests/urls/tests_asset.py
https://github.com/breatheco-de/breatheco-de/issues/6643
=> add solution url to asset serializer

breathecode/mentorship/templates/book_session.html, breathecode/mentorship/tests/urls_shortner/tests_slug.py, breathecode/mentorship/views.py, breathecode/notify/templates/base.html
https://github.com/breatheco-de/breatheco-de/issues/6087
=> Redesign mentoring session schedule page

breathecode/events/views.py
https://github.com/breatheco-de/breatheco-de/issues/6869
=> add event checkin activity to me_event_id_join url

breathecode/activity/tests/urls/v2/tests_academy_activity.py, breathecode/activity/views.py
https://github.com/breatheco-de/breatheco-de/issues/6954
=> sort activities by timestamp

breathecode/registry/serializers.py, breathecode/registry/tests/urls/tests_academy_asset.py, breathecode/registry/tests/urls/tests_asset.py
https://github.com/breatheco-de/breatheco-de/issues/6768
=> add related assets to AssetSerializer

breathecode/events/serializers.py, breathecode/events/tests/urls/tests_academy_event_id.py
https://github.com/breatheco-de/breatheco-de/issues/7035
=> add asset to event academy small serializer

breathecode/marketing/views.py
=> Added recaptcha decorator

breathecode/marketing/views.py
=> temprarily remove validate_captcha decorator

breathecode/registry/tasks.py
https://github.com/breatheco-de/breatheco-de/issues/6786
=> remove the deletion of cloud file

breathecode/services/google_cloud/big_query.py
https://github.com/breatheco-de/breatheco-de/issues/6875
https://github.com/breatheco-de/breatheco-de/issues/6869
=> fix bug when merging schema

breathecode/registry/management/commands/create_asset_thumbnail.py
https://github.com/breatheco-de/breatheco-de/issues/6786
=> Add script for preview generation of assets withput preview

breathecode/marketing/views.py
=> add validate captcha decorator again

breathecode/marketing/urls.py, breathecode/marketing/views.py, breathecode/utils/decorators/validate_captcha.py
https://github.com/breatheco-de/breatheco-de/issues/7150
=> Add environment variable to disable recaptcha validation

breathecode/utils/decorators/validate_captcha.py
=> put prints to validate recaptcha

breathecode/utils/decorators/validate_captcha.py
=> put more prints

breathecode/assignments/serializers.py, breathecode/assignments/tests/urls/tests_task.py, breathecode/assignments/tests/urls/tests_task_id.py, breathecode/assignments/tests/urls/tests_user_me_task.py
https://github.com/breatheco-de/breatheco-de/issues/6989
=> add assignment_telemetry to TaskGETSerializer

breathecode/registry/actions.py, breathecode/registry/fixtures/dev_data.json, breathecode/registry/tests/actions/tests_clean_h1s.py
https://github.com/breatheco-de/breatheco-de/issues/7122
=> Fix Clean h1s

breathecode/marketing/views.py, breathecode/services/google_cloud/recaptcha.py, breathecode/utils/decorators/__init__.py, breathecode/utils/decorators/validate_captcha_challenge.py
https://github.com/breatheco-de/breatheco-de/issues/7172
=> Recaptcha v2

Pipfile, Pipfile.lock, breathecode/assignments/serializers.py, breathecode/assignments/tests/urls/tests_final_project_cohort.py
https://github.com/breatheco-de/breatheco-de/issues/7307
=> Add profile picture to Final project serializer

breathecode/authenticate/serializers.py, breathecode/authenticate/tests/urls/tests_app_user.py, breathecode/authenticate/tests/urls/tests_app_user_id.py, breathecode/authenticate/tests/urls/tests_user_me.py
https://github.com/breatheco-de/breatheco-de/issues/7450
=> add date_joined to user_me serializer

breathecode/registry/serializers.py, breathecode/registry/tests/urls/v1/tests_asset.py
https://github.com/breatheco-de/breatheco-de/issues/7413
=> use AssetMidSerializer for technologies serializer

breathecode/mentorship/tests/urls_shortner/tests_meet_slug_service_slug.py, breathecode/utils/decorators/consume.py
https://github.com/breatheco-de/breatheco-de/issues/7473
=> fix consumables redirection link

breathecode/notify/serializers.py, breathecode/notify/tests/urls/tests_slack_team.py, breathecode/notify/urls.py, breathecode/notify/views.py
https://github.com/breatheco-de/breatheco-de/issues/7413
=> endpoint to get slack teams by academies

breathecode/registry/serializers.py, breathecode/registry/tests/urls/v1/tests_asset.py, breathecode/registry/views.py
https://github.com/breatheco-de/breatheco-de/issues/7745
=> Add expandable serializer by querystring

breathecode/registry/serializers.py, breathecode/registry/tests/urls/v1/tests_asset.py
https://github.com/breatheco-de/breatheco-de/issues/7745
=> fix expandable serializer bug with lessons ipynb

breathecode/assignments/tasks.py, breathecode/assignments/tests/tasks/tests_sync_cohort_user_tasks.py, breathecode/assignments/tests/urls/tests_sync_cohort_tasks.py, breathecode/assignments/urls.py, breathecode/assignments/views.py
https://github.com/breatheco-de/breatheco-de/issues/7773
=> Add task and endpoint to sync all users in a cohort

breathecode/mentorship/templates/pick_service.html
I made a formatting using `shift` + `alt` + `f`, that's why it appears I changed everything
=> fix styling problem in mentorship services

breathecode/provisioning/serializers.py, breathecode/provisioning/tests/urls/tests_academy_id_provisioning_profile.py, breathecode/provisioning/urls.py, breathecode/provisioning/views.py
https://github.com/breatheco-de/breatheco-de/issues/7843
=> Provisioning vendors

breathecode/registry/serializers.py, breathecode/registry/tests/urls/v1/tests_academy_asset.py, breathecode/registry/tests/urls/v1/tests_asset.py
https://github.com/breatheco-de/breatheco-de/issues/7713
=> add aliases to asset detail

breathecode/authenticate/management/commands/set_permissions.py
=> 🚑 adding upload_media permission

breathecode/authenticate/serializers.py, breathecode/authenticate/tests/urls/tests_academy_member_id_invite.py, breathecode/authenticate/tests/urls/tests_academy_user_invite.py, breathecode/authenticate/tests/urls/tests_member_invite_resend_id.py
https://github.com/breatheco-de/breatheco-de/issues/7697
=> add cohort id to invite serializer

breathecode/registry/serializers.py, breathecode/registry/tests/urls/v1/tests_academy_asset.py, breathecode/registry/tests/urls/v1/tests_asset.py, breathecode/registry/tests/urls/v2/tests_academy_asset_slug.py
=> add learnpack_deploy_url to the seriilizer and test

breathecode/registry/serializers.py
=> adding new key on AssetHookSerialier

breathecode/authenticate/serializers.py, breathecode/authenticate/tests/urls/tests_subscribe.py
https://github.com/breatheco-de/breatheco-de/issues/7887
=> Add marketing consent to subscribtions serializer

breathecode/authenticate/tests/urls/tests_me_profile_academy_invite.py, breathecode/authenticate/urls.py, breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/7888
=> Endpoint to accept my pending ProfileAcademy

breathecode/registry/serializers.py, breathecode/registry/tests/urls/v1/tests_asset_context.py, breathecode/registry/urls/v1.py, breathecode/registry/views.py
https://github.com/breatheco-de/breatheco-de/issues/7913
=> Add endpoint to fetch asset context

breathecode/registry/tests/urls/v1/tests_asset_context.py, breathecode/registry/views.py
https://github.com/breatheco-de/breatheco-de/issues/7954
=> Create asset ai context on fetch if it is none

breathecode/authenticate/views.py
=> ♻️ using set_query_parameter

breathecode/registry/serializers.py, breathecode/registry/tests/urls/v1/tests_academy_asset.py
https://github.com/breatheco-de/breatheco-de/issues/8002
=> add template_url and dependencies to the assets serializer

breathecode/registry/views.py
=> adding visibility filter

breathecode/admissions/serializers.py
Reverts breatheco-de/apiv2#1514
=> Revert "add academy to cohort user hook serializer"

breathecode/admissions/receivers.py
https://github.com/breatheco-de/breatheco-de/issues/7592
=> add micro cohort users in the same as the main cohort user

breathecode/admissions/management/commands/fix_assets_slug_in_syllabus_json.py, breathecode/assignments/management/commands/correct_tasks_alias_slug.py
https://github.com/breatheco-de/breatheco-de/issues/8151
=> Syllabus commands

breathecode/assignments/management/commands/update_telemetry_assets_slug.py
https://github.com/breatheco-de/breatheco-de/issues/8245
=> add command to update asset slug in assignments telemetry

breathecode/registry/actions.py
=> refactor to remove title when haaving !?

breathecode/admissions/serializers.py
https://github.com/breatheco-de/breatheco-de/issues/8124
=> Expand admissions me serializer to include permissions and settings

breathecode/registry/management/commands/generate_asset_context.py
https://github.com/breatheco-de/breatheco-de/issues/8004
=> add flag --all to generate_asset_context command

breathecode/payments/tests/urls/tests_consumable_checkout.py, breathecode/payments/views.py
https://github.com/breatheco-de/breatheco-de/issues/8179
=> Allow to buy void consumables

breathecode/feedback/serializers.py, breathecode/feedback/views.py
Create and Add GetSurveySerializer in SurveyView
=> Add GetSurveySerializer in SurveyView

breathecode/authenticate/tests/urls/v1/tests_email_verification.py, breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/8381
=> Fix status code in Email verification

breathecode/authenticate/tests/urls/v1/tests_email_verification.py, breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/8381
=> Fix validation on email verification

breathecode/registry/serializers.py, breathecode/registry/tests/urls/v1/tests_asset.py
=> ❇️ allow tempalte_url on public view

breathecode/authenticate/views.py
=> Add prints to examine user info

breathecode/authenticate/views.py
=> fix the scopes for simple auth

breathecode/authenticate/management/commands/testing.py, breathecode/authenticate/views.py
=> Get google profile info from a different service

breathecode/authenticate/views.py
=> fix key bug

.env.example, breathecode/authenticate/actions.py, breathecode/authenticate/serializers.py, breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/8536
=> sync users on rigobot after userinvite is created

breathecode/authenticate/views.py, breathecode/utils/api_view_extensions/extensions/pagination_extension.py, breathecode/utils/header_limit_offset_pagination.py
https://github.com/orgs/breatheco-de/projects/7/views/1?filterQuery=avanegas&pane=issue&itemId=94817791&issue=breatheco-de%7Cbreatheco-de%7C8310
=> Download csv of students is not working

breathecode/authenticate/tests/urls/v1/tests_academy_settings_log.py, breathecode/authenticate/urls/v1.py, breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/8353
=> Endpoint to retrieve github error log from academy auth settings

breathecode/payments/flags.py, breathecode/payments/tests/urls/tests_me_service_blocked.py, breathecode/payments/urls.py, breathecode/payments/views.py
https://github.com/breatheco-de/breatheco-de/issues/8388
=> Add endpoint to query user blocked services

breathecode/payments/views.py
=> Add academy_id in subscription view

breathecode/registry/serializers.py, breathecode/registry/tests/urls/v1/tests_asset.py
=> adding dependencies

breathecode/authenticate/views.py
=> Fix bug with querystrings in redirect url

breathecode/authenticate/tests/urls/v1/tests_google_callback.py, breathecode/authenticate/tests/urls/v1/tests_google_token.py, breathecode/authenticate/views.py
=> Fix google auth tests

breathecode/assignments/models.py
https://github.com/breatheco-de/breatheco-de/issues/8488
=> Fix bug when updating the reviewed_at property

breathecode/events/tests/urls/tests_eventype.py, breathecode/events/views.py
=> adding lang to eventtype

breathecode/admissions/admin.py, breathecode/admissions/management/commands/add_user_to_micro_cohorts.py
https://github.com/breatheco-de/breatheco-de/issues/7592
=> Add command to add users to main cohort

breathecode/admissions/receivers.py
https://github.com/breatheco-de/breatheco-de/issues/8765
=> Validate if a syllabus has mandatory projects before graduating students

breathecode/certificate/views.py
https://github.com/breatheco-de/breatheco-de/issues/8413
=> Throw error on certificate token if cohort user is finantial_status late

breathecode/admissions/serializers.py, breathecode/events/tests/management/commands/tests_close_live_classes.py
https://github.com/breatheco-de/breatheco-de/issues/8798
=> Add checkin to event serializer

breathecode/admissions/serializers.py
https://github.com/breatheco-de/breatheco-de/issues/8798
=> Fix event checkin

breathecode/registry/serializers.py, breathecode/registry/views.py
https://github.com/breatheco-de/breatheco-de/issues/8827
https://github.com/breatheco-de/breatheco-de/issues/8947
=> Add telemetry stats to serializer

breathecode/authenticate/tests/urls/v1/tests_password_token.py, breathecode/authenticate/views.py
https://github.com/breatheco-de/breatheco-de/issues/8991
=> Determine the app for the Email password settings

breathecode/payments/services/stripe.py
=> chaging amount on invoice record to non cents amount

breathecode/payments/admin.py, breathecode/payments/management/commands/remove_repeated_payment_contacts.py, breathecode/payments/tests/management/commands/tests_remove_repeated_paymen_contacts.py
=> adding script that checks repeated payment contacts and remove latest

breathecode/payments/views.py
=> 🐛 fix bug with lookup on payment methods

breathecode/payments/services/stripe.py, breathecode/payments/urls/v1.py, breathecode/payments/urls/v2.py, breathecode/payments/views.py, breathecode/urls.py
=> ✨ payment methods updates when user changes card

breathecode/authenticate/management/commands/set_permissions.py, breathecode/payments/management/commands/grant_plan_permissions.py, breathecode/payments/models.py, breathecode/payments/receivers.py, breathecode/payments/signals.py
=> ✨ create group Paid Students

breathecode/provisioning/actions.py
=> bug on github bills

breathecode/authenticate/management/commands/create_academy_roles.py
=> 🚑  adding get_academy_auth_settings to academy_coordinators

breathecode/assignments/urls.py, breathecode/assignments/views.py
=> ♻️ changes on urls and views names to use get on flag endpoint

breathecode/assignments/serializers.py, breathecode/assignments/tasks.py
=> ♻️ changes on task and serializer conditions

breathecode/marketing/tests/urls/tests_course.py, breathecode/marketing/urls.py, breathecode/marketing/views.py
=> creating new endpoint to get course translations

breathecode/payments/views.py
=> change on admin view to get plans

breathecode/payments/actions.py
=> solving bug related to void consumables

breathecode/assignments/tasks.py, breathecode/assignments/views.py, breathecode/registry/views.py
=> 🐛  clean asset and update readme

breathecode/admissions/tasks.py, breathecode/admissions/views.py
=> removing stages that are not correct

breathecode/admissions/admin.py
=> I believed too much on ai result so im fixing it

breathecode/payments/views.py
=> 🐛 solving bug related to a view not returning cancelled but valid subs

breathecode/assignments/serializers.py, breathecode/assignments/tasks.py
=> solving the bug related to approved flags going to rejected

breathecode/registry/actions.py
=> improving getting solution from a repo

breathecode/assignments/management/commands/delete_repositories_from_ended_cohorts.py
=> improving delete repo to delete .git repos

breathecode/admissions/serializers.py, breathecode/admissions/views.py, breathecode/authenticate/actions.py, breathecode/authenticate/management/commands/create_academy_roles.py, breathecode/authenticate/management/commands/seed_groups.py, breathecode/authenticate/management/commands/set_permissions.py, breathecode/authenticate/receivers.py, breathecode/payments/actions.py, breathecode/payments/models.py, breathecode/payments/receivers.py
=> adding new profile academy role and user will not have grupo paid student if only have free sub

breathecode/authenticate/models.py, breathecode/authenticate/receivers.py, breathecode/authenticate/signals.py
=> removing groups when changin academy user

breathecode/payments/management/commands/export_influencer_referral_comission.py
=> command to aprox how much should be paid to influencer for referrals

breathecode/payments/admin.py
=> adding bulk action to create consumables

breathecode/payments/tasks.py
=> :bug: adding fallback in case valid until is not available use next payment at

breathecode/activity/actions.py, breathecode/commission/actions.py, breathecode/commission/serializers.py, breathecode/commission/tasks.py, breathecode/commission/views.py
=> :recycle: refactor to the view to better legibility

breathecode/commission/views.py
=> view testing a small changes to them to avoid human errors

breathecode/authenticate/views.py
Issue: https://github.com/breatheco-de/breatheco-de/issues/9753
=> Fix of broken url when pressing Continue to sign in on the pick_password view

breathecode/admissions/receivers.py, breathecode/certificate/actions.py
=> solving bug related to pending -3

breathecode/monitoring/views.py
=> logs to see why is not getting the hook

breathecode/payments/receivers.py
=> if error it should edit status text

breathecode/registry/views.py
=> adding changes to urls

breathecode/payments/views.py
=> 🐛 adding academy_id to headrs

breathecode/payments/actions.py, breathecode/payments/management/commands/remove_coupon_plans.py
Issue: https://github.com/breatheco-de/breatheco-de/issues/9480
=> Improved conditional to add coupons to bag
